# Generated by Django 6.0.2 on 2026-02-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default='aluno@email.com', max_length=150),
        ),
    ]
