# Generated by Django 6.0.2 on 2026-02-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_curso_aluno_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
